### PR TITLE
Python 3 Version

### PR DESCRIPTION
**Pull request by koskorya**
I currently have this version running [here.](https://rkosko-app-test.appspot.com/) It's behind okta oidc so let me know if you need access or want to test things out.

### CODE REVIEW

**Comment by sjaensch** [comment]
I'd love to test things out @koskorya, could you give me access?

**Comment by sjaensch** [comment]
Also please check out the travis build. No tests have been executed due to a requirements issue. Let's make sure they are executed and pass.

**Comment by koskorya** [comment]
@sjaensch you should be good to log in now and I also granted you access to the project in gcp.

Also tests aren't something I have much experience with. I'll play around with them and make as much progress as I can.

**Comment by sjaensch** [comment]
@koskorya I can't seem to access your version. I even tried opening the link in an incognito window to make sure that no prior state is causing this. I was redirected to Okta, I logged in and was redirected back to your app, with it showing a white page with "Not authorized" as the only content on it.

**Comment by koskorya** [comment]
@sjaensch my fault I added you to the wrong group within okta. You now should be all set this time

**Comment by sjaensch** [comment]
Hey @koskorya , first of all, I have access now and it seems to work, that's great news!

OTOH, I'm not sure how exactly we can proceed here. The fact that you reformatted the code with black makes it extremely hard to review, plus tests are not running at all. I think both of those things need to be fixed before we can continue.

1. Please undo the black formatting. Such a wide-ranging change to format (but not function) should always be done in a separate PR.
2. Once that's done, I can start collaborating and get the tests to at least run; we can then work on fixing them if they do fail.

**Comment by koskorya** [comment]
@sjaensch yes very fair point and my apologies about that. I can re-submit a proper PR with the necessary changes and exclude the formatting ones. 

As for the tests, I kept struggling with import errors for most of them. Also there is a NoseGAE test package that is only for python 2 and I wasn't able to find a replacement. Maybe we can pair program on this next week sometime at your convenience.

**Pull request closed without merging**
